-- Initialize the Vaccinator PostgreSQL database
-- This script runs automatically when the container starts for the first time

-- Create additional extensions if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create indexes for better performance (will be created after tables are auto-generated by Hibernate)
-- These will be applied after the application creates the tables

-- Grant additional permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vaccinator_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO vaccinator_user;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO vaccinator_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO vaccinator_user;

-- Create a function to add indexes after table creation
CREATE OR REPLACE FUNCTION add_performance_indexes() RETURNS void AS $$
BEGIN
    -- Add indexes for who_prequalified_vaccines table (if exists)
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'who_prequalified_vaccines') THEN
        -- Index for date searches
        CREATE INDEX IF NOT EXISTS idx_who_vaccines_date_prequalification 
        ON who_prequalified_vaccines(date_of_prequalification DESC);
        
        -- Index for vaccine type searches
        CREATE INDEX IF NOT EXISTS idx_who_vaccines_vaccine_type 
        ON who_prequalified_vaccines(vaccine_type);
        
        -- Index for manufacturer searches
        CREATE INDEX IF NOT EXISTS idx_who_vaccines_manufacturer 
        ON who_prequalified_vaccines(manufacturer);
        
        -- Composite index for search
        CREATE INDEX IF NOT EXISTS idx_who_vaccines_search 
        ON who_prequalified_vaccines(vaccine_type, commercial_name, manufacturer);
        
        -- Full text search index
        CREATE INDEX IF NOT EXISTS idx_who_vaccines_fulltext 
        ON who_prequalified_vaccines USING gin(
            to_tsvector('english', 
                coalesce(vaccine_type, '') || ' ' || 
                coalesce(commercial_name, '') || ' ' || 
                coalesce(manufacturer, '')
            )
        );
        
        RAISE NOTICE 'Performance indexes created for who_prequalified_vaccines table';
    ELSE
        RAISE NOTICE 'who_prequalified_vaccines table does not exist yet - indexes will be created later';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Log successful initialization
DO $$
BEGIN
    RAISE NOTICE 'Vaccinator PostgreSQL database initialized successfully';
    RAISE NOTICE 'Database: vaccinator_postgres';
    RAISE NOTICE 'User: vaccinator_user';
    RAISE NOTICE 'Extensions and permissions configured';
END $$;
