version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vaccinator-mongo-dev
    environment:
      MONGO_INITDB_DATABASE: vaccinator_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - vaccinator-net

volumes:
  mongo_data:

networks:
  vaccinator-net:
    driver: bridge 